name: CI (React app)

on:
  pull_request:
    paths:
      - frontend/**

defaults:
  run:
    working-directory: frontend

jobs:
  frontend_tasks:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        task: [lint, audit, test, build]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: 22.14.0

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 10.7.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.task }}
        run: |
          if [ "${{ matrix.task }}" == "audit" ]; then
            pnpm audit
          elif [ "${{ matrix.task }}" == "test" ]; then
            pnpm test
          elif [ "${{ matrix.task }}" == "lint" ]; then
            pnpm lint:ci
          elif [ "${{ matrix.task }}" == "build" ]; then
            pnpm build
          fi

      - name: Upload build artifacts
        if: matrix.task == 'build'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: frontend-build
          path: frontend/dist/
          retention-days: 7
